name: Build, Test and Deploy

on:
  workflow_dispatch:
  
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalação de dependências 
        run: npm install
      - name: Teste
        run: npm test
    
